backend:
  name: github
  repo: vajayjay/netlify-test

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: Aktuelles
    folder: content/news
    create: true
    fields:
      - { name: path, label: Path, default: news } 
      - { name: date, label: Datum, widget: date }
      - { name: body, label: Nachricht, widget: markdown }

  - label: Öffnungszeiten
    name: times
    files:
    - label: Öffnungszeiten
      name: times
      file: content/times.md
      fields:
        - { name: path, label: Path, default: times }
        - { name: monday, label: Montag, widget: text }
        - { name: tuesday, label: Dienstag, widget: text }
        - { name: wednesday, label: Mittwoch, widget: text }
        - { name: thursday, label: Donnerstag, widget: text }
        - { name: friday, label: Freitag, widget: text }