backend:
  name: github
  repo: vajayjay/netlify-test

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: Aktuelles
    folder: news
    create: true
    fields:
      - { name: path, label: Path, widget: path, default: news }
      - { name: date, label: Datum, widget: date }
      - { name: body, label: Nachricht, widget: markdown }

  - name: times
    label: Öffnungszeiten
    folder: times
    create: true
    fields:
      - { name: path, label: Path, widget: path, default: times }
      - { name: monday, label: Montag, widget: datetime }
      - { name: tuesday, label: Dienstag, widget: text }
      - { name: wednesday, label: Mittwoch, widget: markdown }
      - { name: thursday, label: Donnerstag, widget: markdown }
      - { name: friday, label: Freitag, widget: markdown }
