backend:
  name: github
  repo: vajayjay/netlify-test

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: Aktuelles
    folder: news
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Datum, widget: date }
      - { name: body, label: Nachricht, widget: markdown }